### ISSUE TITLE
Unable to estabilish connection with Facepunch.Steamworks 2.3.3

### ISSUE THREAD

**Issue by Yazir** [Pieeer1/SteamMultiplayerPeer#12]
While the example seems to work as it should, with its included libraries, updating Facepunch.Steamworks to a newer version (2.3.3 from nuget) produces a connection error.
**Steps to reproduce**
1. Download, unpack this repo
2. **remove** from .csproj
```
<None Include="Facepunch/Facepunch.Steamworks.Posix.dll" />
<None Include="Facepunch/Facepunch.Steamworks.Win64.dll" />
```
**delete** `./Facepunch` folder

**add**
`<PackageReference Include="facepunch.steamworks" Version="2.3.3" />`

3. `dotnet restore` in root directory
4. **replace** steam_api.dll and steam_api64.dll with versions from [facepunch steamworks release](https://github.com/Facepunch/Facepunch.Steamworks/releases/tag/2.3.2) (Unity/redistributable_bin/*)

run project, run exported project on separate steam account
host lobby, connect to lobby on second account, lobby joining works, but it breaks on trying to estabilish socket connection

error:
```
ERROR: System.Collections.Generic.KeyNotFoundException: The given key '76561198043000362' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Steam.SteamMultiplayerPeer.ProcessPing(SetupPeerPayload receive, UInt64 sender) in C:\personal\godot\projectsv4\SteamMultiplayerPeer-master\Steam\SteamMultiplayerPeer.cs:line 257
   at Steam.SteamMultiplayerPeer._Poll() in C:\personal\godot\projectsv4\SteamMultiplayerPeer-master\Steam\SteamMultiplayerPeer.cs:line 249
   at Godot.MultiplayerPeerExtension.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret)
   at Steam.SteamMultiplayerPeer.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in C:\personal\godot\projectsv4\SteamMultiplayerPeer-master\.godot\mono\temp\obj\ExportDebug\win-x64\Godot.SourceGenerators\Godot.SourceGenerators.ScriptMethodsGenerator\Steam.SteamMultiplayerPeer_ScriptMethods.generated.cs:line 270
   at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr godotObjectGCHandle, godot_string_name* method, godot_variant** args, Int32 argCount, godot_variant_call_error* refCallError, godot_variant* ret)
```

SteamMultiplayerPeer.cs:373 -> AddConnection receives steamId equal to 0

----
Other than stability and feature completeness, it is useful to have facepunch as a nuget package, since exporting for different platforms is more streamlined.

**Comment by Pieeer1** [comment]
Yeah I am using a pretty hyper specific version of both steamworks and the facepunch setup. At some point my idea is to upgrade the steam works api to the newest version, and rewrite the facepunch library pretty heavily. Unfortunately the nuget package version is missing some undocumented functionality or is out of sync with newer steamworks version IIRC.

**Comment by Yazir** [comment]
I assume [this](https://github.com/finepointcgi/Facepunch.Steamworks/releases/tag/1.0) is the source of the libraries? If so it is worth pointing out in the readme.

2. https://gist.github.com/Pieeer1/559c1de3a8c7110249a0f45b630e8b43

**Comment by Pieeer1** [comment]
That is the source of the steam binaries but the facepunch setup was pulled from a branch that was a significant amount ahead of their nuget release. Getting the actual source and documenting it is a good idea though, I'll see if I can track where I got it from.

**Comment by anchikai** [comment]
@Pieeer1 is there any progress on the source of the Facepunch dll? I'm trying to mod Facepunch so that I can pull usernames using [`ISteamFriends.GetFriendPersonaName`](https://partner.steamgames.com/doc/api/ISteamFriends#GetFriendPersonaName)

The method would probably be added in the [`Steamworks.SteamFriends`](https://github.com/Facepunch/Facepunch.Steamworks/blob/master/Facepunch.Steamworks/SteamFriends.cs) class

**Comment by Pieeer1** [comment]
It was from their dev branch, I’d have to look into it still. Facepunch doesn’t really maintain a solid release cadence with the steam api changes so you have to custom match.
