### ISSUE TITLE
USER ERROR: FATAL: Condition "script.is_null()" is true.

### ISSUE THREAD

**Issue by Yazir** [Pieeer1/SteamMultiplayerPeer#13]
An error might randomly occur on the hosting client.

```
USER ERROR: FATAL: Condition "script.is_null()" is true.
   at: tie_user_managed_to_unmanaged (modules/mono/csharp_script.cpp:1402)
```

More complete stacktrace

```
ERROR: FATAL: Condition "script.is_null()" is true.
   at: tie_user_managed_to_unmanaged (modules/mono/csharp_script.cpp:1402)
Fatal error. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Godot.NativeInterop.NativeFuncs.godotsharp_internal_tie_user_managed_to_unmanaged(IntPtr, IntPtr, Godot.NativeInterop.godot_ref*, Godot.NativeInterop.godot_bool)
   at Godot.NativeInterop.InteropUtils.TieManagedToUnmanaged(Godot.GodotObject, IntPtr, Godot.StringName, Boolean, System.Type, System.Type)
   at Godot.GodotObject.ConstructAndInitialize(IntPtr (), Godot.StringName, System.Type, Boolean)
   at Godot.RefCounted..ctor()
   at Steam.SteamPacketPeer..ctor(Byte[], TransferModeEnum)
   at Steam.SteamMultiplayerPeer._PutPacketScript(Byte[])
   at Godot.MultiplayerPeerExtension.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name ByRef, Godot.NativeInterop.NativeVariantPtrArgs, Godot.NativeInterop.godot_variant ByRef)
   at Steam.SteamMultiplayerPeer.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name ByRef, Godot.NativeInterop.NativeVariantPtrArgs, Godot.NativeInterop.godot_variant ByRef)
   at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr, Godot.NativeInterop.godot_string_name*, Godot.NativeInterop.godot_variant**, Int32, Godot.NativeInterop.godot_variant_call_error*, Godot.NativeInterop.godot_variant*)
   at Godot.NativeInterop.NativeFuncs.godotsharp_method_bind_call(IntPtr, IntPtr, Godot.NativeInterop.godot_variant**, Int32, Godot.NativeInterop.godot_variant_call_error ByRef)
   at Godot.NativeCalls.godot_icall_2_778(IntPtr, IntPtr, Godot.NativeInterop.godot_string_name, Godot.Variant[], Godot.NativeInterop.godot_string_name)
   at Godot.Node.Rpc(Godot.StringName, Godot.Variant[])
   at Huriko.TransportMagnate.GameLogic.ProcessTurn()
   at Godot.Callable.<From>g__Trampoline|1_0(System.Object, Godot.NativeInterop.NativeVariantPtrArgs, Godot.NativeInterop.godot_variant ByRef)
   at Godot.DelegateUtils.InvokeWithVariantArgs(IntPtr, Void*, Godot.NativeInterop.godot_variant**, Int32, Godot.NativeInterop.godot_variant*)

```

Game is working as usual, nothing new is being added other than amount of data sent every second (eg. last sent byte array was 7kb right before crash). 
Seems to happen randomly after half an hour or more of gameplay. I'll observe new instances of this crash.

method failing in source: https://github.com/godotengine/godot/blob/master/modules/mono/csharp_script.cpp#L1392

Could this be an engine error?

**Comment by Pieeer1** [comment]
Hmm the Packet is a RefCounted looks like that might have some issue with the GC… fun, I will have to play around with it.

**Comment by Yazir** [comment]
Removing RefCounted from SteamPacketPeer seems to have fixed the crash. I did not test it thoroughly, will update if it still crashes.

**Comment by Pieeer1** [comment]
Yeah that aligns, RefCounted can be fun sometimes.

**Comment by craethke** [comment]
Getting the same exception on the server, after about 5 min, from an Rpc method that's called every physics step.

Interestingly, per the stack trace, the error happens when calling the RefCounted constructor - I'm not familiar enough with the C# interop stuff to be able to trace where that null value comes from.

```
================================================================
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.5.1.stable.mono.official (f62fdbde15035c5576dad93e586201f4d41ef0cb)
Dumping the backtrace. Please include this when reporting the bug on: https://github.com/godotengine/godot/issues
[1] /usr/lib64/dotnet/shared/Microsoft.NETCore.App/10.0.0/libcoreclr.so(+0x6069b0) [0x7f5de1e069b0] (??:0)
[2] /lib64/libc.so.6(+0x1a2c0) [0x7f5e6f91b2c0] (??:0)
[3] /workspace/Godot/Godot_v4.5.1-stable_mono_linux_x86_64/Godot_v4.5.1-stable_mono_linux.x86_64() [0x10ef63b] (??:0)
[4] [0x7f5d637c9e79] (??:0)
-- END OF C++ BACKTRACE --
================================================================
ERROR: FATAL: Condition "script.is_null()" is true.
   at: tie_user_managed_to_unmanaged (modules/mono/csharp_script.cpp:1431)
C# backtrace (most recent call first):
    [0] void Godot.NativeInterop.InteropUtils.TieManagedToUnmanaged(Godot.GodotObject, nint, Godot.StringName, bool, System.Type, System.Type) (/root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/InteropUtils.cs:73)
    [1] void Godot.GodotObject.ConstructAndInitialize(System.IntPtr(Godot.NativeInterop.godot_bool), Godot.StringName, System.Type, bool) (/root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/GodotObject.base.cs:61)
    [2] Godot.RefCounted..ctor() (/root/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/RefCounted.cs:29)
    [3] Steam.SteamPacketPeer..ctor(System.Byte[], Godot.MultiplayerPeer+TransferModeEnum) (/workspace/stella/addons/SteamMultiplayerPeer/Steam/SteamPacketPeer.cs:7)
    [4] Godot.Error Steam.SteamMultiplayerPeer._PutPacketScript(System.Byte[]) (/workspace/stella/addons/SteamMultiplayerPeer/Steam/SteamMultiplayerPeer.cs:312)
    [5] bool Godot.MultiplayerPeerExtension.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name&, Godot.NativeInterop.NativeVariantPtrArgs, Godot.NativeInterop.godot_variant&) (/root/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/MultiplayerPeerExtension.cs:394)
    [6] bool Steam.SteamMultiplayerPeer.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name&, Godot.NativeInterop.NativeVariantPtrArgs, Godot.NativeInterop.godot_variant&) (/workspace/stella/.godot/mono/temp/obj/Debug/Godot.SourceGenerators/Godot.SourceGenerators.ScriptMethodsGenerator/Steam.SteamMultiplayerPeer_ScriptMethods.generated.cs:270)
    [7] Godot.NativeInterop.godot_bool Godot.Bridge.CSharpInstanceBridge.Call(nint, Godot.NativeInterop.godot_string_name*, Godot.NativeInterop.godot_variant**, int, Godot.NativeInterop.godot_variant_call_error*, Godot.NativeInterop.godot_variant*) (/root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/CSharpInstanceBridge.cs:24)
    [8] Godot.NativeInterop.godot_variant Godot.NativeInterop.NativeFuncs.godotsharp_method_bind_call(nint, nint, Godot.NativeInterop.godot_variant**, int, Godot.NativeInterop.godot_variant_call_error&) (/root/godot/modules/mono/glue/GodotSharp/GodotSharp/Godot.SourceGenerators.Internal/Godot.SourceGenerators.Internal.UnmanagedCallbacksGenerator/Godot.NativeInterop.NativeFuncs.generated.cs:388)
    [9] int Godot.NativeCalls.godot_icall_2_873(nint, nint, Godot.NativeInterop.godot_string_name, System.ReadOnlySpan`1[Godot.Variant], Godot.NativeInterop.godot_string_name) (/root/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/NativeCalls.cs:7778)
    [10] Godot.Error Godot.Node.Rpc(Godot.StringName, Godot.Variant[]) (/root/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/Node.cs:2154)
    [11] void Humanoid.SendSnapshot() (/workspace/stella/Scripts/Humanoid.cs:888)
    [12] void Humanoid._PhysicsProcess(double) (/workspace/stella/Scripts/Humanoid.cs:454)
```

My SendSnapshot method isn't doing anything crazy, just looks like this:
```
    private void SendSnapshot()
    {
        Rpc(nameof(ReceiveSnapshot), new Godot.Collections.Dictionary<string, Variant> {
            { "pos", GlobalPosition },
            { "vel", LinearVelocity },
            // ...
        });
    }
```

**Comment by Yazir** [comment]
I'm still running on the script and after the change (afair remove inheritance of RefCounted), I didn't see any issues or memory leaks. 
Im also running ticks on physics time.

Go to SteamPacketPeer file and remove ": RefCounted" and forget about it.

**Comment by Pieeer1** [comment]
Newest release changes from a class with refcounted extension to a struct, which aligns more with the data model anyways.
